"""Render ARRANGEMENT.md from an Arrangement."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from hapax_arrange import __version__
from hapax_arrange.model import Arrangement
from hapax_arrange.writer import _filename


def render(arrangement: Arrangement, outdir: Path) -> Path:
    outdir.mkdir(parents=True, exist_ok=True)
    path = outdir / "ARRANGEMENT.md"
    path.write_text(render_markdown(arrangement))
    return path


def render_markdown(arrangement: Arrangement) -> str:
    n_unique = sum(len(s) for s in arrangement.pattern_slots.values())
    n_raw = len(arrangement.sections) * len(arrangement.tracks)
    parts = [
        _header(arrangement),
        _summary(arrangement, n_unique, n_raw),
        _warnings(arrangement),
        _track_map(arrangement),
        _pattern_slots(arrangement),
        _sections_matrix(arrangement),
        _song_order(arrangement),
        _import_checklist(arrangement),
        _section_build(arrangement),
        _song_build(arrangement),
    ]
    return "\n\n".join(parts).rstrip() + "\n"


def _header(arrangement: Arrangement) -> str:
    return (
        f"# Hapax Import Plan: {arrangement.song_name}\n\n"
        f"Generated by hapax-arrange {__version__} on {date.today().isoformat()}."
    )


def _summary(arrangement: Arrangement, n_unique: int, n_raw: int) -> str:
    section_names = ", ".join(s.name for s in arrangement.sections)
    num, den = arrangement.time_signature
    return (
        "## Summary\n\n"
        f"- Source: `{arrangement.input_path}` "
        f"(PPQ {arrangement.ppq}, {arrangement.tempo_bpm:.1f} BPM, {num}/{den})\n"
        f"- Tracks: {len(arrangement.tracks)} source → {len(arrangement.tracks)} Hapax\n"
        f"- Sections: {len(arrangement.sections)} ({section_names})\n"
        f"- Unique patterns after dedup: {n_unique} (from {n_raw})\n"
        f"- Imports required: {n_unique}"
    )


def _warnings(arrangement: Arrangement) -> str:
    body = ["## Warnings"]
    if not arrangement.warnings and not arrangement.errors:
        body.append("\nNone.")
    else:
        for e in arrangement.errors:
            body.append(f"\n- **ERROR**: {e}")
        for w in arrangement.warnings:
            body.append(f"\n- {w}")
    return "".join(body)


def _track_map(arrangement: Arrangement) -> str:
    rows = ["## Track Map", "", "| Hapax Track | Source Track | Name | Type |", "|---|---|---|---|"]
    for tm in sorted(arrangement.tracks, key=lambda t: t.hapax_track):
        rows.append(f"| {tm.hapax_track} | {tm.source_track} | {tm.name} | {tm.kind} |")
    return "\n".join(rows)


def _pattern_slots(arrangement: Arrangement) -> str:
    out = ["## Pattern Slots"]
    for hapax_track in sorted(arrangement.pattern_slots.keys()):
        tm = next(t for t in arrangement.tracks if t.hapax_track == hapax_track)
        out.append(f"\n### Track {hapax_track} — {tm.name}\n")
        out.append("| Slot | Length | Used In |")
        out.append("|---|---|---|")
        for slot in arrangement.pattern_slots[hapax_track]:
            used = ", ".join(slot.sections_using)
            out.append(f"| P{slot.slot_index:02d} | {slot.length_bars:.2f} bars | {used} |")
    return "\n".join(out)


def _sections_matrix(arrangement: Arrangement) -> str:
    header = (
        ["| Section |"] + [f" T{t.hapax_track} |" for t in arrangement.tracks] + [" Duration |"]
    )
    sep = ["|---|"] + ["---|" for _ in arrangement.tracks] + ["---|"]
    rows = ["## Sections", "", "".join(header).rstrip(), "".join(sep).rstrip()]
    for section in arrangement.sections:
        cells = [f"| {section.name} |"]
        for tm in arrangement.tracks:
            slot = section.track_to_slot.get(tm.hapax_track)
            cells.append(f" {'—' if slot is None else f'P{slot:02d}'} |")
        cells.append(f" {section.duration_bars:.2f} bars |")
        rows.append("".join(cells).rstrip())
    rows.append("")
    rows.append(
        '"—" means the track is inactive in that section — leave that Hapax track on any '
        "pattern slot or mute it for that section."
    )
    return "\n".join(rows)


def _song_order(arrangement: Arrangement) -> str:
    lines = ["## Song Order", ""]
    for i, section in enumerate(arrangement.sections, start=1):
        lines.append(f"{i}. {section.name} — {section.duration_bars:.2f} bars")
    return "\n".join(lines)


def _import_checklist(arrangement: Arrangement) -> str:
    lines = [
        "## Import Checklist",
        "",
        "Copy `MIDI/` to your Hapax SD card under `/MIDI/` and eject. Then for each row:",
        "",
        "1. Select the track",
        "2. Select the pattern slot (`Hold Pattern + matrix pad`)",
        "3. `2ND + track` → scroll to `Import` → browse → pick the file",
        "",
    ]
    for hapax_track in sorted(arrangement.pattern_slots.keys()):
        for slot in arrangement.pattern_slots[hapax_track]:
            fname = _filename(hapax_track, slot)
            lines.append(f"- [ ] Track {hapax_track}, Slot {slot.slot_index}: `MIDI/{fname}`")
    return "\n".join(lines)


def _section_build(arrangement: Arrangement) -> str:
    lines = [
        "## Section Build",
        "",
        "For each section, on the matrix pads:",
        "1. Set each track to its listed pattern slot",
        "2. `Main encoder → SAVE SECTION` → name it",
        "",
    ]
    for section in arrangement.sections:
        parts = []
        for tm in arrangement.tracks:
            slot = section.track_to_slot.get(tm.hapax_track)
            parts.append(f"T{tm.hapax_track}:{'—' if slot is None else f'P{slot:02d}'}")
        lines.append(f"- [ ] {section.name}: {', '.join(parts)}")
    return "\n".join(lines)


def _song_build(arrangement: Arrangement) -> str:
    lines = [
        "## Song Build",
        "",
        "`Press Pattern` to reach the Song tab. Add each section in order with the "
        "listed duration:",
        "",
    ]
    for i, section in enumerate(arrangement.sections, start=1):
        lines.append(f"{i}. [ ] {section.name} ({section.duration_bars:.2f} bars)")
    lines.append("")
    lines.append("Set `Mode` to `PLAY SONG` or `LOOP SONG` and hit ▶.")
    return "\n".join(lines)
